services:
  nifi:
    build: .
    image: my-nifi
    ports:
      - "8080:8080"   # NiFi UI
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - remote-postgres
      - local-postgres

  remote-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: remote_user
      POSTGRES_PASSWORD: remote_pass
      POSTGRES_DB: remote_db
    ports:
      - "5432:5432"
    volumes:
      - ./remote-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  local-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: local_db
    ports:
      - "5433:5432"  # Expose on a different host port to avoid conflicts
    volumes:
      - ./local-db/init.sql:/docker-entrypoint-initdb.d/init.sql
